# Generated by Django 3.2.25 on 2024-07-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project'),
        ),
    ]
