# Generated by Django 3.2.25 on 2024-07-16 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
